### PR TITLE
[xpack user] Add support for elasticsearch v6

### PR DESCRIPTION
**Pull request by sangeethdba**

### CODE REVIEW

**Comment by sangeethdba** [comment]
https://github.com/olivere/elastic/releases/tag/v6.2.36


i got the put role added to v6 in oliver repo. @phillbaker

**Comment by sangeethdba** [comment]
@phillbaker please review when you have some time thanks for all the help

**Comment by phillbaker** [comment]
@sangeethdba that's great - I assume you mean [put user](https://github.com/olivere/elastic/commit/dfa03a816415f60213b577f13d208d73fdb4c444). Unfortunately, delete and get user are also needed to finish implementation of the resource on v6.

See: 
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c28d2dec3f5c366de4d694149a1d6489471ea79b/es/resource_elasticsearch_xpack_user.go#L316

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c28d2dec3f5c366de4d694149a1d6489471ea79b/es/resource_elasticsearch_xpack_user.go#L286

**Comment by sangeethdba** [comment]
Ok I will create or for those two options as well .
Is my pull request I created for for put user is good ?

**Comment by sangeethdba** [comment]
@phillbaker get user and delete user is also added  
https://github.com/olivere/elastic/releases/tag/v6.2.37

**Comment by sangeethdba** [comment]
@phillbaker would you please apprve

**Comment by phillbaker** [comment]
You'll need to bump the dependency in go.mod and update go.sum for these methods to be available, otherwise this won't build. Please include updates for all three methods in this pull request.

**Comment by sangeethdba** [comment]
Ok will do shortly

**Comment by sangeethdba** [comment]
@phillbaker i made required changes

**Comment by sangeethdba** [comment]
@phillbaker  would you please let me know the error ?

**Pull request merged**
