### PR TITLE
Added watch resource

### PR DESCRIPTION
**Pull request by mattcsg**
Extended terraform-provider-elasticsearch to include support for managing Watches. Support was added for Elastic 6 only.

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks! Just thinking this through - since watches are only in xpack and the integration tests are against opensource ES, is it even possible to write tests for these endpoints?

**Comment by phillbaker** [comment]
It looks like this commit https://github.com/olivere/elastic/commit/779af8d01771233d0ba20ee89168e5bcca512b4f on olivere/elastic added support for testing xpack.

**Comment by mattcsg** [comment]
Thanks @phillbaker. I wasn't sure if you even wanted to support watches in the provider, but we had a need so I extended your work to support them. No worries if you don't want to merge this in. Thanks for building the provider. It was a great jump start for us!

**Comment by phillbaker** [comment]
Thanks! I've cherry-picked your commit and added tests. Closing this as it's on master.

**Pull request closed without merging**
