### PR TITLE
Fix ids normalization for monitors in opensearch 1.1+

### PR DESCRIPTION
**Pull request by kroussou**
This PR suppresses the diff described in #305.

### CODE REVIEW

**Review by phillbaker — COMMENTED** [review]
thanks, this code change looks good to me, it failed on CI due to formatting of the test terraform code, can you update?

**Comment by kroussou** [comment]
@phillbaker I've tried to fix formatting. Could you please rerun CI to verify

**Comment by kroussou** [comment]
It seems my changes won't pass CI anyway. Tests are updated for opensearch v1.1.0 and should fail with v1.0.0 used in CI pipeline. Tests against anything other than opensearch are also expected to fail. 

Is it OK to switch CI to v1.1.0?
For the other case I can add version check to skip test in unsupported environments.

**Comment by phillbaker** [comment]
Yes, please update 1.0 to 1.1 and add the version check.

**Comment by kroussou** [comment]
I also had to add opensearch 1.1 support to `opendistro_ism_policy` test which also caused CI failure

**Comment by kroussou** [comment]
@phillbaker Is there something I can do to have this merged?

**Review by secustor — APPROVED** [review]

**Comment by phillbaker** [comment]
I squashed and rebased the work here into b96f0a42eb8cbf7fe9b89153702816c973fa481a, it's now merge on master.

**Pull request closed without merging**
