### PR TITLE
Support ElasticSearch-7.x.x & Use Go Modules instead of Glide

### PR DESCRIPTION
**Pull request by basvandijk**
This is WIP because I haven't tested this yet. Hopefully the travis tests will catch any mistakes.

### CODE REVIEW

**Comment by basvandijk** [comment]
Mmm apparently travis doesn't run for draft PR's. I'll turn it into a regular PR so that travis will run.

**Comment by basvandijk** [comment]
The test-suite currently fails in `resourceElasticsearchPutKibanaObject` when running with elasticsearch >= 7.0.1 with the error: 

```
Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [_doc, visualization]
```

[According to Elastic](https://discuss.elastic.co/t/rejecting-mapping-update-to-kibana-as-the-final-mapping-would-have-more-than-1-type-visualization-doc-error/133557/8) you can't push this directly to ES anymore and you now have to go via a new Kibana API.

So `resource_elasticsearch_kibana_object.go` probably has to target the [Kibana Saved Objects API](https://www.elastic.co/guide/en/kibana/7.1/saved-objects-api.html) rather than the ES API.

**Comment by basvandijk** [comment]
I decided to remove `resource_elasticsearch_kibana_object` since it's not supported by Elasticsearch anymore.

**Comment by phillbaker** [comment]
Thanks for the PR!

In order to not break backward compatibility, I'd prefer to either raise a
"not implemented" error for the kibana object on ES 7 or implement support
- that functionality is important.

**Comment by phillbaker** [comment]
@basvandijk I'm working on cherry-picking commits out of this PR onto master. I'm cursious - why didn't you check in the `go.sum` file?

**Comment by phillbaker** [comment]
Thanks again for the PR! I've cherry-picked commits and released an updated provider: https://github.com/phillbaker/terraform-provider-elasticsearch/releases

**Comment by basvandijk** [comment]
Thanks for the cherry-pick!

**Comment by JPLachance** [comment]
Hello!

I see that the Kibana object resource support was removed for Elasticsearch 7. I don' understand why. From what I'm reading, the only breaking change is [a saved objects structure change](https://www.elastic.co/guide/en/kibana/7.x/breaking-changes-7.0.html#breaking-changes-7.0-saved-objects).

I think that with the correct payload, the `elasticsearch_kibana_object` resource would work.

Unless there is something else that I don't see?

Thanks for your help! 😄

**Comment by phillbaker** [comment]
@JPLachance it might be possible, but not recommended officially! If you'd like to do a PR (with tests), I'd be open to it.

As pointed out above,
> [According to Elastic](https://discuss.elastic.co/t/rejecting-mapping-update-to-kibana-as-the-final-mapping-would-have-more-than-1-type-visualization-doc-error/133557/8) you s Kibana objects directly to ES anymore and you now have to go via a new (well 2 years old by now) Kibana API.
> So `resource_elasticsearch_kibana_object.go` probably has to target the [Kibana Saved Objects API](https://www.elastic.co/guide/en/kibana/7.1/saved-objects-api.html) rather than the ES API.

**Comment by JPLachance** [comment]
Noted!

How can this provider connect to the Kibana API? At the moment, we give the provider the endpoint of the Elasticsearch cluster and most of the time, the Kibana API is at another endpoint.

Is the solution a dedicated Kibana Terraform provider? https://github.com/ewilde/terraform-provider-kibana

Thanks!

**Comment by phillbaker** [comment]
Just noting that 29ef7ec added support for kibana objects using the underlying index 🙈, cherry-picked from https://github.com/phillbaker/terraform-provider-elasticsearch/pull/50. Thanks to @tdegiacinto.

**Pull request closed without merging**
