### PR TITLE
use new _index_template endpoints for ES7

### PR DESCRIPTION
**Pull request by digitalkaoz**
see https://github.com/olivere/elastic/pull/1415

### CODE REVIEW

**Comment by phillbaker** [comment]
Hi, can you elaborate a bit on the intent here?

If I’m understanding correctly, this is compatible only with ES v7.8+. It’d
be a breaking change for other versions.

**Comment by digitalkaoz** [comment]
Mh, yeah you are right, its only 7.8+. The _template endpoint is deprecated and will be removed soon. Maybe check the minor version too?

**Comment by phillbaker** [comment]
That sounds fine to me!

**Comment by phillbaker** [comment]
Hi @digitalkaoz are you able to update this PR?

**Comment by phillbaker** [comment]
Hi @digitalkaoz I'm going to close this PR out since it hasn't been updated. Please re-open if you're able to update.

**Pull request closed without merging**
