### PR TITLE
Migrate to Terraform SDK v1.0.0

### PR DESCRIPTION
**Pull request by Kheldar**
Followed steps at: https://www.terraform.io/docs/extend/plugin-sdk.html#step-1-check-eligibility-for-migration

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks - just to confirm this was done using the migrator tool?

**Comment by Kheldar** [comment]
Yep

**Comment by phillbaker** [comment]
This does not appear to be a break change, from the terraform integration standpoint - am I reading that correctly?

**Comment by Kheldar** [comment]
A few APIs were broken (documented at the bottom of that link), but I don't think you're using any of those.

Otherwise, I think it's just a case where they moved the stuff that was in Terraform-core out into its own library, as-is.

**Comment by phillbaker** [comment]
Thanks!

**Pull request merged**
