### PR TITLE
Added freebsd, darwin, linux, windows, 386, and amd64 to build targets.

### PR DESCRIPTION
**Pull request by Kheldar**

### CODE REVIEW

**Comment by Kheldar** [comment]
Hopefully this solves #16

**Comment by phillbaker** [comment]
Thanks!

Looks like this will produce files in the following form, which will then have the tag appended:

```
- "terraform-provider-elasticsearch_darwin_386"
- "terraform-provider-elasticsearch_darwin_amd64"
- "terraform-provider-elasticsearch_linux_386"
- "terraform-provider-elasticsearch_linux_amd64"
- "terraform-provider-elasticsearch_windows_386.exe"
- "terraform-provider-elasticsearch_windows_amd64.exe"
```

Does that look right?

**Comment by Kheldar** [comment]
Pretty sure, yeah (left my dev laptop at work, so can't check). Might require a minor change to put the tag before the `.exe` on Windows.

**Comment by phillbaker** [comment]
Sorry, had an edit for my comment and forgot to hit enter. I think terraform does have some conventions:  https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions

Mind switching to something like: 

https://github.com/ewilde/terraform-provider-kibana/blob/958ba1618738013bd12ff2952e91f258bf87eecc/GNUmakefile#L35-L36

**Comment by Kheldar** [comment]
I _could_ use that structure, but I don't actually know enough about Travis to make the `deploy` step work with those folders. Any suggestions?

**Comment by Kheldar** [comment]
@phillbaker I'm now matching the format used for releases on the repo you linked (minus the `.zip`).

If I'm reading the documentation correctly, the folders thing only applies at the installed location - there's not much we can do about that from the Travis or GH Releases end.

**Comment by Kheldar** [comment]
Specifically, on my system:
```
$ gox -os "freebsd darwin linux windows" -arch "386 amd64" -output="terraform-provider-elasticsearch_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
```
gives
```
 $ ls -1 terraform-provider-elasticsearch*
terraform-provider-elasticsearch_v1.2.3_darwin_386
terraform-provider-elasticsearch_v1.2.3_darwin_amd64
terraform-provider-elasticsearch_v1.2.3_freebsd_386
terraform-provider-elasticsearch_v1.2.3_freebsd_amd64
terraform-provider-elasticsearch_v1.2.3_linux_386
terraform-provider-elasticsearch_v1.2.3_linux_amd64
terraform-provider-elasticsearch_v1.2.3_windows_386.exe
terraform-provider-elasticsearch_v1.2.3_windows_amd64.exe
```

**Comment by Kheldar** [comment]
I set up the deployment on my company's fork. You can check the releases here:
https://github.com/packetloop/terraform-provider-elasticsearch/releases

**Comment by phillbaker** [comment]
Thanks! Makes sense.

**Comment by Kheldar** [comment]
Thanks :)

Also, you might want to push a tag or something so that a release gets generated.

**Comment by phillbaker** [comment]
Done! See: https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v0.6.0

**Pull request merged**
