### PR TITLE
feature: add support for ingest pipeline

### PR DESCRIPTION
**Pull request by jfroche**
waiting for https://github.com/olivere/elastic/pull/1128 to be merged

### CODE REVIEW

**Comment by phillbaker** [comment]
This will close https://github.com/phillbaker/terraform-provider-elasticsearch/issues/24, thanks!

**Comment by phillbaker** [comment]
@jfroche any update here?

**Comment by phillbaker** [comment]
Looks like the branch was merged into elastic and released in https://github.com/olivere/elastic/releases/tag/v7.0.5!

**Comment by jfroche** [comment]
Indeed, v7 seems ok using the new release. v5 and v6 are broken as the fix was not backported to v5 and v6 release of `olivere/elastic`. I asked the author here: https://github.com/olivere/elastic/pull/1128

**Comment by phillbaker** [comment]
Looks like the upstream library has been updated for v5 and v6! Mind updating your branch? Would be great to get this in.

**Comment by jfroche** [comment]
Right, thank you for reminder. I will fix it this week

**Comment by phillbaker** [comment]
Woot, thanks for getting this updated!

**Pull request merged**
