### PR TITLE
Add support for ElasticSearch 7.8+ component templates

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
This PR is an attempt to add support for component templates. It's based on a PR yet to be merged in the elastic go library used by this provider: https://github.com/olivere/elastic/pull/1458.

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks @yann-soubeyrand for the contribution! It might be good to ping olivere directly on that PR to get it reviewed. 

I haven't take a close look at this PR yet, let me know when the upstream change is merged.

**Comment by phillbaker** [comment]
upstream pr was merged and released in 7.0.25

**Comment by phillbaker** [comment]
Cherry-picked this and updated the ref in 7a6207d50a60a55bcc9d1b653599311b5dfd529f. Thanks for the contribution!

**Comment by yann-soubeyrand** [comment]
You’re welcome, and thanks for the merge ;-)

**Pull request closed without merging**
