### PR TITLE
Add odfe role and roles mapping

### PR DESCRIPTION
**Pull request by tdegiacinto**

### CODE REVIEW

**Comment by phillbaker** [comment]
I think this depends on the searchguard code that is incorporated into opendistro based on floragunn's code. That code is currently the subject of a [copyright infringement lawsuit it looks like](https://www.elastic.co/blog/dear-search-guard-users-including-amazon-elasticsearch-service-open-distro-and-others).

It'll probably take quite some time to resolve that lawsuit, but it does make we wonder about the long term support of OpenDistro for the security suite. There doesn't seem to be much comment from AWS: https://discuss.opendistrocommunity.dev/t/elastic-suing-searchguard/1457

**Comment by JPLachance** [comment]
Hello @phillbaker,

AWS just released their [fine-grained data access management for their AWS Elasticsearch service](https://aws.amazon.com/about-aws/whats-new/2020/02/configure-fine-grained-data-access-with-amazon-elasticsearch-service/). 

This PR from our team adds the support for the configuration of AWS Elasticsearch roles and role mappings (that are in fact ODFE Security roles).

AWS strongly stands behind ODFE and does not plan to drop the support for their new fine-grained data access management feature anytime soon.

Can your re-consider merging this pull request? 😄 If so, we will try to address merge conflicts.

Thank you very much for this provider!

**Comment by phillbaker** [comment]
@JPLachance that makes sense to me - I'm willing to merge an updated PR. Before we merge, I'd like to update the resource names and file names to be, `resource_elasticsearch_opendistro_*`. Trying to centralize resources that differ live only in xpack and opendistro under their respective names.

**Comment by JPLachance** [comment]
Hello @tdegiacinto,

Can you rework your initial PR to adapt it to changes requested by Phillip?

Thank you!

**Comment by phillbaker** [comment]
Squashed and cherry-picked as 13e1cc9988f746517cdb18007f82d9e18ee6aeb6

**Pull request closed without merging**
