### PR TITLE
Add ism

### PR DESCRIPTION
**Pull request by tdegiacinto**
Hi, in complement of #45 here is a PR to add resources for ILM.

### CODE REVIEW

**Comment by phillbaker** [comment]
@tdegiacinto thanks for the PR. Just to clarify - this PR is for the opendistro index version of lifecycle management, with the resource named `elasticsearch_odfe_policy`, correct?

**Comment by phillbaker** [comment]
The docs for this API are here: https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/.

**Comment by tdegiacinto** [comment]
Indeed this PR is for adding opendistro index lifecycle management.

**Comment by fsperling** [comment]
Is there something missing to get this merged?

**Comment by springerigor** [comment]
I would appreciate having this PR merged.

**Comment by phillbaker** [comment]
This has been squashed and cherry-picked onto master as 6e8a88f. Thanks for the effort here.

**Comment by springerigor** [comment]
Awesome @phillbaker 🙇‍♂️ Waiting for a released version 🙂

**Pull request closed without merging**
