### PR TITLE
Import roles

### PR DESCRIPTION
**Pull request by mindbat**
WIP. Carry-over from https://github.com/phillbaker/terraform-provider-elasticsearch/pull/58

Part of the work for #57

### CODE REVIEW

**Comment by mindbat** [comment]
Taking a stab in the dark: Perhaps we need to implement some `flatteners` for the `indices` and `applications` for a Role, per the [example in the terraform provider docs](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-a-more-complex-read)?

**Comment by phillbaker** [comment]
> Taking a stab in the dark: Perhaps we need to implement some `flatteners` for the `indices` and `applications` for a Role, per the [example in the terraform provider docs](https://www.terraform.io/docs/extend/writing-custom-providers.html#implementing-a-more-complex-read)?

Yup, that's exactly right. I haven't been able to dig into it too much, but that is the right approach.

**Comment by mindbat** [comment]
@phillbaker Got a first pass of a _working_ roles import done (finally)!

It's super-rough, because I'm just feeling my way forward in the dark here...But the new import tests pass, which is progress :)

I'll work on cleaning it up, but can you take a look when you can and see if the general approach I've taken is the right one?

**Comment by phillbaker** [comment]
Great, I’ll check it out!

**Comment by phillbaker** [comment]
Sorry for the slowness here - do you mind `go fmt`ing these files?

I'm not sure if releasing this would be a breaking change for folks using these fields now - I'm not opposed to releasing it, but I might try to get some other breaking changes in at the same time.

**Comment by mindbat** [comment]
> Sorry for the slowness here - do you mind go fmting these files?

No worries! I've `gofmt`'d the files; sorry I thought I'd done that earlier :/

> not sure if releasing this would be a breaking change for folks using these fields now

Since we're changing the way `field_security` is represented, then probably? Which is awkward, I agree.

When releasing such breaking changes, what's the usual recommendation? Will they have to do a `terraform delete` with the old version, and re-apply with the new? Or will it be possible to use a `terraform taint` to get things working with the new release?

**Comment by phillbaker** [comment]
> When releasing such breaking changes, what's the usual recommendation? Will they have to do a terraform delete with the old version, and re-apply with the new? Or will it be possible to use a terraform taint to get things working with the new release?

Logistically, folks could probably do a `terraform state rm`  and then a `terraform import` - especially that these resources now support import 😀. On the provider side, I'm going to make this a major version bump and add a change log.

**Pull request merged**
