### PR TITLE
Add script resource

### PR DESCRIPTION
**Pull request by k3v142**
Add a resource to manage stored scripts:
```tf
resource "elasticsearch_script" "test_script" {
  script_id = "my_script"
  lang      = "painless"
  source    = "Math.log(_score * 2) + params.my_modifier"
}
```

### CODE REVIEW

**Review by phillbaker — COMMENTED** [review]
Hello, thanks for the contribution. A few thoughts:
* While the approach to just store JSON works, it's not really the way terraform suggests building providers (see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/93). A better approach, especially because the number of attributes on this resource is so low would be to create attributes for the language and source and build the json body.
* If that's really not feasible, at a minimum, we should have the attribute be the script object, not the entire JSON body

**Comment by k3v142** [comment]
@phillbaker Hello, thanks for your comment. I've made some changes and I would be thankful if you review it.

**Comment by phillbaker** [comment]
This looks good, but the added test is failing. I don't see an obvious issue, but looks like the state isn't being updated properly.

**Comment by k3v142** [comment]
@phillbaker Could you please rerun test?

**Comment by phillbaker** [comment]
Thanks for this, merging!

**Pull request merged**
