### PR TITLE
feat(user): add support for xpack user

### PR DESCRIPTION
**Pull request by jfroche**
on elastic v7

refs #36 

still depend on unmerged feature (pull request here: https://github.com/olivere/elastic/pull/1204)

### CODE REVIEW

**Comment by phillbaker** [comment]
Looking forward to it, thanks1

**Comment by phillbaker** [comment]
Looks like this will be in the upcoming 7.0.9: https://github.com/olivere/elastic/milestone/47

**Comment by jfroche** [comment]
It should be ok now

**Comment by phillbaker** [comment]
Thanks!

**Pull request merged**
