### PR TITLE
Add the possibility to provide index settings

### PR DESCRIPTION
**Pull request by luismartins-td**
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # elasticsearch_index.test_v1 must be replaced
-/+ resource "elasticsearch_index" "test_v1" {
        aliases                           = jsonencode(
            {
                test = {}
            }
        )
        codec                             = "best_compression"
        force_destroy                     = false
      ~ id                                = "test_v1" -> (known after apply)
      - load_fixed_bitset_filters_eagerly = false -> null
        name                              = "test_v1"
        number_of_replicas                = "4"
        number_of_shards                  = "5"
        refresh_interval                  = "30s"
      - routing_partition_size            = 0 -> null
      + settings                          = jsonencode(
            {
              + index = {
                  + analysis = {
                      + analyzer  = {
                          + default          = {
                              + filter    = [
                                  + "lowercase",
                                  + "asciifolding",
                                ]
                              + tokenizer = "standard"
                            }
                          + full_text_search = {
                              + filter    = [
                                  + "lowercase",
                                  + "asciifolding",
                                ]
                              + tokenizer = "custom_ngram_tokenizer"
                            }
                        }
                      + tokenizer = {
                          + custom_ngram_tokenizer = {
                              + max_gram = "4"
                              + min_gram = "3"
                              + type     = "ngram"
                            }
                        }
                    }
                }
            }
        ) # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks for the PR! I'm not opposed to adding this, but some index settings are already available as individual keys that can be configured, it'd more consistent to add this similar to those other keys. This is because some of these settings are dynamic (can be changed on the index) while others are static (require closing or creating a new index and re-importing):

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/29b85d2e21bf79f88a8f19dfc20f6ccf22e1041c/resource_elasticsearch_index.go#L18-L33

It looks like you're specifically trying to add the `analysis` setting? It looks like in most cases that requires closing/reopening or recreating the index, so that would be a static setting.

**Comment by luismartins-td** [comment]
Yes, I understand what you are saying. I just add the settings field this way because every time that you want a new setting you need to add it on the code right? Or do you have an example to add this to the index side?

Thank you.

**Comment by phillbaker** [comment]
> every time that you want a new setting you need to add it on the code
right?

That’s correct. The extra code trades off with making sure that the
provider doesn’t let the user try to make changes that the data store won’t
accept (eg in many cases making analysis changes). There aren’t too many
settings / they aren’t added that often, so I don’t think the amount of
code required is that burdensome.

**Comment by luismartins-td** [comment]
Ok. So the solution is: Make a new PR with the analysis field on staticSettingsKeys? I'm going to check which options could make sense too. Or do you advise to do using another approach?

**Comment by phillbaker** [comment]
Yes, that’d be great, thanks!

**Comment by luismartins-td** [comment]
Hi @phillbaker,

When I try to add the analysis field on staticSettingsKeys I get this error:
Error: elastic: Error 400 (Bad Request): unknown setting [index.analysis] please check that any required plugins are installed, or check the breaking changes documentation for removed settings [type=illegal_argument_exception]

Do you know why?
How do you suggest to add these fields?

Thank you

**Comment by phillbaker** [comment]
Can you push the code that you have as a separate draft PR perhaps? That’s
easier to debug.

**Comment by luismartins-td** [comment]
Hi @phillbaker 

I just added the field on 'staticSettingsKeys' and on 'configSchema'.

But I think that this field could not be added this way right?

Do you have a suggestion?

Thank you

**Comment by phillbaker** [comment]
This should be supported now via the new index attributes `analysis_analyzer` and analysis_tokenizer`, introduced in 611975d85b4385e236b772ad717e77ee6929f0e2. Thanks for illustrating the need.

**Pull request closed without merging**
